### ISSUE TITLE
Cannot 'Select All the Vertices Assigned to the Active Vertex Group', using mask's VGroup (2.80 stable, 2.81 beta)

### ISSUE THREAD

**Issue by SuitableForWork** [bookyakuno/-Blender-#4]
I've just tried this on both 2.8 and 2.81 and cannot select the geometry with active vertex groups created by the mask in edit mode. Instead, when pressing the 'select' button on the vertex groups list, the entire mesh is selected. For instance, the new quadremesher from exoside can use material groups to define the shape, but without this function, the re-topology process is harder.

Kind regards,

Simon.

**Comment by blenderguy22** [comment]
how do u even open it, i cant
